"""Initial complete schema

Revision ID: 24606730aa4e
Revises: 
Create Date: 2026-05-03 16:43:48.675203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24606730aa4e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_heartbeats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('instance_id', sa.String(length=128), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_agent_heartbeats_event_id')
    )
    with op.batch_alter_table('agent_heartbeats', schema=None) as batch_op:
        batch_op.create_index('ix_agent_heartbeats_agent_created_at', ['agent_name', 'created_at'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('line_id', sa.String(length=32), nullable=True),
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_alert_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_incidents_severity'),
    sa.CheckConstraint("status IN ('NEW_ALERT', 'DIAGNOSING', 'DIAGNOSED', 'PROPOSING_REPAIR', 'REPAIR_READY', 'VALIDATING', 'VALIDATED', 'SIMULATING', 'SIMULATED', 'PENDING_HUMAN_APPROVAL', 'APPROVED', 'REJECTED', 'MODIFIED', 'EXECUTING', 'COMPLETED', 'ABORTED')", name='ck_incidents_status'),
    sa.ForeignKeyConstraint(['source_alert_id'], ['monitor_alerts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correlation_id', name='uq_incidents_correlation_id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_status_updated_at', ['status', 'updated_at'], unique=False)

    op.create_table('line_health_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('overall_health', sa.String(length=16), nullable=False),
    sa.Column('total_produced', sa.Integer(), nullable=False),
    sa.Column('total_rate_per_min', sa.Float(), nullable=False),
    sa.Column('active_fault_count', sa.Integer(), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_line_health_snapshots_event_id')
    )
    with op.batch_alter_table('line_health_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_line_health_snapshots_line_created_at', ['line_id', 'created_at'], unique=False)

    op.create_table('monitor_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('line_id', sa.String(length=32), nullable=True),
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_monitor_alerts_severity'),
    sa.CheckConstraint("status IN ('open', 'acknowledged', 'cleared')", name='ck_monitor_alerts_status'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_monitor_alerts_event_id')
    )
    with op.batch_alter_table('monitor_alerts', schema=None) as batch_op:
        batch_op.create_index('ix_monitor_alerts_line_station_created_at', ['line_id', 'station_id', 'created_at'], unique=False)
        batch_op.create_index('ix_monitor_alerts_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('rag_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=128), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', name='uq_rag_documents_document_id')
    )
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.create_index('ix_rag_documents_source_path', ['source_path'], unique=False)

    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'answered', 'expired', 'cancelled')", name='ck_approval_requests_status'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_approval_requests_event_id'),
    sa.UniqueConstraint('request_id', name='uq_approval_requests_request_id')
    )
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.create_index('ix_approval_requests_status_created_at', ['status', 'created_at'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('urgency', sa.String(length=32), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('alternative_causes_json', sa.JSON(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_diagnoses_event_id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index('ix_diagnoses_incident_created_at', ['incident_id', 'created_at'], unique=False)

    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source_agent', sa.String(length=64), nullable=False),
    sa.Column('line_id', sa.String(length=32), nullable=True),
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_incident_events_event_id')
    )
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.create_index('ix_incident_events_correlation_created_at', ['correlation_id', 'created_at'], unique=False)
        batch_op.create_index('ix_incident_events_incident_created_at', ['incident_id', 'created_at'], unique=False)

    op.create_table('optimizer_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('recommendation_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('scope_line_id', sa.String(length=32), nullable=True),
    sa.Column('scope_station_id', sa.String(length=64), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('recommendation_json', sa.JSON(), nullable=False),
    sa.Column('expected_impact_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_optimizer_recommendations_event_id'),
    sa.UniqueConstraint('recommendation_id', name='uq_optimizer_recommendations_recommendation_id')
    )
    with op.batch_alter_table('optimizer_recommendations', schema=None) as batch_op:
        batch_op.create_index('ix_optimizer_recommendations_created_at', ['created_at'], unique=False)

    op.create_table('repair_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('proposal_version', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_repair_proposals_event_id')
    )
    with op.batch_alter_table('repair_proposals', schema=None) as batch_op:
        batch_op.create_index('ix_repair_proposals_incident_created_at', ['incident_id', 'created_at'], unique=False)

    op.create_table('human_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('approval_request_id', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('operator_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('modification_json', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVE', 'REJECT', 'MODIFY')", name='ck_human_decisions_decision'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_human_decisions_event_id')
    )
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_human_decisions_incident_created_at', ['incident_id', 'created_at'], unique=False)

    op.create_table('repair_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('option_rank', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters_to_change_json', sa.JSON(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=True),
    sa.Column('trade_offs_json', sa.JSON(), nullable=False),
    sa.Column('command_candidates_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['repair_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repair_options', schema=None) as batch_op:
        batch_op.create_index('ix_repair_options_proposal_id', ['proposal_id'], unique=False)

    op.create_table('validation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.Column('concerns_json', sa.JSON(), nullable=False),
    sa.Column('hard_rule_passed', sa.Boolean(), nullable=False),
    sa.Column('llm_review_passed', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict IN ('PASS', 'FAIL')", name='ck_validation_results_verdict'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['repair_proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_validation_results_event_id')
    )
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.create_index('ix_validation_results_incident_created_at', ['incident_id', 'created_at'], unique=False)

    op.create_table('execution_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('guard_report_json', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('rollback_status', sa.String(length=32), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'ABORTED')", name='ck_execution_runs_status'),
    sa.ForeignKeyConstraint(['decision_id'], ['human_decisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_execution_runs_event_id')
    )
    with op.batch_alter_table('execution_runs', schema=None) as batch_op:
        batch_op.create_index('ix_execution_runs_incident_created_at', ['incident_id', 'created_at'], unique=False)

    op.create_table('rag_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis_id', sa.Integer(), nullable=True),
    sa.Column('repair_option_id', sa.Integer(), nullable=True),
    sa.Column('rag_document_id', sa.Integer(), nullable=True),
    sa.Column('usefulness_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rag_document_id'], ['rag_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repair_option_id'], ['repair_options.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_rag_feedback_created_at', ['created_at'], unique=False)

    op.create_table('simulation_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('validation_id', sa.Integer(), nullable=True),
    sa.Column('go_no_go', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('predicted_cycle_time_delta', sa.Float(), nullable=True),
    sa.Column('predicted_pass_rate_delta', sa.Float(), nullable=True),
    sa.Column('predicted_throughput_delta', sa.Float(), nullable=True),
    sa.Column('predicted_fault_risk_delta', sa.Float(), nullable=True),
    sa.Column('side_effects_json', sa.JSON(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("go_no_go IN ('GO', 'NO_GO', 'INCONCLUSIVE')", name='ck_simulation_results_go_no_go'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validation_id'], ['validation_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_simulation_results_event_id')
    )
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.create_index('ix_simulation_results_incident_created_at', ['incident_id', 'created_at'], unique=False)

    op.create_table('command_audit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('execution_run_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('line_id', sa.String(length=32), nullable=True),
    sa.Column('station_id', sa.String(length=64), nullable=True),
    sa.Column('command_payload_json', sa.JSON(), nullable=False),
    sa.Column('publish_status', sa.String(length=32), nullable=False),
    sa.Column('response_payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_run_id'], ['execution_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_command_audit_event_id')
    )
    with op.batch_alter_table('command_audit', schema=None) as batch_op:
        batch_op.create_index('ix_command_audit_topic_created_at', ['topic', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('command_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_command_audit_topic_created_at')

    op.drop_table('command_audit')
    with op.batch_alter_table('simulation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_simulation_results_incident_created_at')

    op.drop_table('simulation_results')
    with op.batch_alter_table('rag_feedback', schema=None) as batch_op:
        batch_op.drop_index('ix_rag_feedback_created_at')

    op.drop_table('rag_feedback')
    with op.batch_alter_table('execution_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_execution_runs_incident_created_at')

    op.drop_table('execution_runs')
    with op.batch_alter_table('validation_results', schema=None) as batch_op:
        batch_op.drop_index('ix_validation_results_incident_created_at')

    op.drop_table('validation_results')
    with op.batch_alter_table('repair_options', schema=None) as batch_op:
        batch_op.drop_index('ix_repair_options_proposal_id')

    op.drop_table('repair_options')
    with op.batch_alter_table('human_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_human_decisions_incident_created_at')

    op.drop_table('human_decisions')
    with op.batch_alter_table('repair_proposals', schema=None) as batch_op:
        batch_op.drop_index('ix_repair_proposals_incident_created_at')

    op.drop_table('repair_proposals')
    with op.batch_alter_table('optimizer_recommendations', schema=None) as batch_op:
        batch_op.drop_index('ix_optimizer_recommendations_created_at')

    op.drop_table('optimizer_recommendations')
    with op.batch_alter_table('incident_events', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_events_incident_created_at')
        batch_op.drop_index('ix_incident_events_correlation_created_at')

    op.drop_table('incident_events')
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_index('ix_diagnoses_incident_created_at')

    op.drop_table('diagnoses')
    with op.batch_alter_table('approval_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_approval_requests_status_created_at')

    op.drop_table('approval_requests')
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_rag_documents_source_path')

    op.drop_table('rag_documents')
    with op.batch_alter_table('monitor_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_monitor_alerts_status_created_at')
        batch_op.drop_index('ix_monitor_alerts_line_station_created_at')

    op.drop_table('monitor_alerts')
    with op.batch_alter_table('line_health_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_line_health_snapshots_line_created_at')

    op.drop_table('line_health_snapshots')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_status_updated_at')

    op.drop_table('incidents')
    with op.batch_alter_table('agent_heartbeats', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_heartbeats_agent_created_at')

    op.drop_table('agent_heartbeats')
    # ### end Alembic commands ###
